#!/bin/bash

# Path:        ~/.dotfiles/i3/bin/i3battery.sh
# Created:     2018-07-16, 14:17    @x200
# Last update: 2019-03-02, 23:05:24 @x200
# Doc:         get battery info for i3blocks

ACPI=`acpi -b | sed 's/,//g'`
STATE=`echo $ACPI | awk '{print $3}'`
TIME=`echo $ACPI | awk '{print $5}'`
TIME="${TIME%:*}"
[[ "$STATE" = "Discharging" ]] && STATE="" || STATE=" " 
PERCENT=`echo $ACPI | awk '{print $4}'`
PERC=${PERCENT%\%}
FGCOLOR=$(awk '/^*urgent/ {print $2}' $HOME/.Xresources)

if (( $PERC < 10 )); then
    echo "<span color='$FGCOLOR'>  $PERC $STATE</span>"
elif (( $PERC < 50 )); then
    echo "  $PERC $STATE"
elif (( $PERC < 75 )); then
    echo "  $PERC $STATE"
elif (( $PERC < 85 )); then
    echo "  $PERC $STATE"
elif (( $PERC <= 100 )); then
    echo "  $PERC $STATE"
fi

case $BLOCK_BUTTON in
    1) [[ -z $STATE ]] && notify-send "BATTERY:" "$TIME left to discharge" || notify-send "BATTERY:" "$TIME left to full charge";;
esac

