#!/bin/bash

# Path:        ~/.dotfiles/i3/bin/i3battery.sh
# Created:     16.07.18, 14:17    @x200
# Last update: 26.07.18, 18:27:58 @x200

# Doc:

ACPI=`acpi -b | sed 's/,//g'`
#echo $ACPI | awk '{print $3 " " $4 " " $5}'
# NAME=${MYVAR%:*}  # retain the part before the colon
# NAME=${NAME##*/}  # retain the part after the last slash
# echo $NAME
STATE=`echo $ACPI | awk '{print $3}'`
TIME=`echo $ACPI | awk '{print $5}'`
TIME="${TIME%:*}"
[[ "$STATE" = "Discharging" ]] && STATE="" || STATE="  " 
PERCENT=`echo $ACPI | awk '{print $4}'`
PERC=${PERCENT%\%}

if (( $PERC < 10 )); then
    echo "<span color='#FF0000'>  $PERCENT$STATE</span>"
elif (( $PERC < 50 )); then
    echo "<span color='#ececec'>  $PERCENT$STATE</span>"
elif (( $PERC < 75 )); then
    echo "<span color='#ececec'>  $PERCENT$STATE</span>"
elif (( $PERC < 85 )); then
    echo "<span color='#ececec'>  $PERCENT$STATE</span>"
elif (( $PERC <= 100 )); then
    echo "<span color='#ececec'>  $PERCENT$STATE</span>"
fi

case $BLOCK_BUTTON in
    1) [[ -z $STATE ]] && notify-send "BATTERY:" "$TIME left to discharge" || notify-send "BATTERY:" "$TIME left to full charge";;
esac

# BUTTON CLICK → time
    
	# if ($percent < 20) {
	# 	print "#FF0000\n";
	# } elsif ($percent < 40) {
	# 	print "#FFAE00\n";
	# } elsif ($percent < 60) {
	# 	print "#FFF600\n";
	# } elsif ($percent < 85) {
	# 	print "#A8FF00\n";
	# }

	# if ($percent < 5) {
	# 	exit(33);
	# }

