#!/bin/bash

# Path:        ~/.dotfiles/i3/bin/i3dp.sh
# Created:     10.07.18, 18:45    @x200
# Last update: 09.08.18, 11:11:39 @x200

# Doc: note: requires dropbox-cli (AUR)

GLYPH=""
#GLYPH=""
#GLYPH=𝔻
NOT=`dropbox-cli status | grep "isn't"`
URU=`dropbox-cli status | grep -i "uruchamianie"`
SYNC=`dropbox-cli status | grep -i "synchronizowanie"`

if [[ $NOT ]]; then
    # <span bgcolor='#00001f26'>
    echo "<span color='#C0392B'> $GLYPH </span>" # 𝔻!
elif [[ $URU ]]; then
    # <span bgcolor='#2980b9'>
    echo "<span color='#ffffff'> $GLYPH </span>" # 𝔻!
elif [[ $SYNC ]]; then
    # <span bgcolor='#ffffff'>
    echo "<span fgcolor='#27AE60'> $GLYPH </span>" #𝔻↓↑
else
    pkill -RTMIN+13 i3blocks
fi

case $BLOCK_BUTTON in
    # left click 
    1) if [[ $NOT ]]; then
           notify-send -u critical "Dropbox status:
--------------" "$(dropbox-cli status)" -i ~/box/Dropbox/.Config/dropbox-logo.png && exit 0
       elif [[ $URU ]]; then
           notify-send "Dropbox status:
--------------" "$(dropbox-cli status)" -i ~/box/Dropbox/.Config/dropbox-logo.png && exit 0
       elif [[ $SYNC ]]; then
           notify-send -u low "Dropbox status:
--------------" "$(dropbox-cli status)" -i ~/box/Dropbox/.Config/dropbox-logo.png && exit 0
       fi
       ;;
esac

