#!/bin/bash

# Path:        ~/.dotfiles/i3/bin/i3dp.sh
# Created:     10.07.18, 18:45    @x200
# Last update: 17.07.18, 10:16:46 @x200

# Doc: note: requires dropbox-cli (AUR)

if [[ `dropbox-cli status | grep "isn't"` ]]; then
    echo "<span bgcolor='#00001f26'><span color='#C0392B'>  </span></span>" # 𝔻!
elif [[ `dropbox-cli status | grep -i "uruchamianie"` ]]; then
    echo "<span bgcolor='#2980b9'><span color='#ffffff'>  </span></span>" # 𝔻!
elif [[ `dropbox-cli status | grep -i "synchronizowanie"` ]]; then
    echo "<span fgcolor='#27AE60'><span bgcolor='#ffffff'>  </span></span>" #𝔻↓↑
else
    pkill -RTMIN+13 i3blocks
fi

