#!/bin/bash

# Path:        ~/.dotfiles/i3/bin/i3loadaverage.sh
# Created:     16.07.18, 15:16    @x200
# Last update: 26.07.18, 18:10:41 @x200

# Doc:
load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"
BGCOLOR=#191f26 # was: #00001f26

#color if load is too high
if [[ $(echo "$cpus <= $load" | bc) = "1" ]]; then
    echo "<span bgcolor='BGCOLOR'><span color='#C0392B'><span weight='bold'> $load</span></span></span>"
else
    echo " $load"
fi

# awk -v cpus=$cpus -v cpuload=$load "
#     BEGIN {
#         if (cpus <= cpuload) {
#             echo \"<span color='#FF0000'> $load </span>\" 
#             exit 33;
#         }
#     }
# "

