#!/bin/bash

# Path:        ~/.dotfiles/i3/scripts/i3mailchecker
# Created:     2019-04-21, 00:43    @lenovo
# Last update: 2019-04-21, 00:44:51 @lenovo
# Doc:         

GLYPH=
MAILBOXES=$HOME/.mail/*/INBOX/new
count=0
new=false

get_date(){
    ls -ltc $1 | sed -n 2p | grep -o "[0-9]\{10\}"
}

new_mail_msg(){
    from=$(awk '/^From:/ {$1=""; print}' $1 2>/dev/null)
    subject=$(awk '/^Subject:/ {$1=""; print}' $1 2>/dev/null)
    [[ -n $from || -n $subject ]] &&\
        notify-send "<b>NEW MAIL ($3)</b>"\
                    "FROM: $from\nSUBJECT:$subject"
}

for dir in $MAILBOXES; do
    box=${dir//$HOME\/.mail\//}
    box_name=${box//\/INBOX\/new/}
    last=~/.config/neomutt/lastmail_$box_name

    unread=$(ls $dir | wc -l)
    count=$((count + unread))

    date_first=$(get_date $dir)

    unread_before=$(sed 1q $last )
    date_before=$(sed -n 2p $last)

    [[ -z $date_first ]] && date_first=0

    echo $unread > $last
    echo $date_first >> $last

    if [[ $unread -eq 0 ]]; then
        continue

    elif [[ $unread -gt $unread_before ]]; then
        new=true
        for file in $(ls -ltcr $dir | awk '{print $8}'); do
            new_mail_msg "$dir/$file"
        done

    else
        for ((i=2; ; i++)); do
            file=$(ls -ltcr $dir | sed -n "$i"p | awk '{print $8}')
            file_date=$(ls $dir/$file | grep -o "[0-9]\{10\}")
            if [[ $file_date -gt $date_before ]]; then
                new=true
                new_mail_msg "$dir/$file"
            else
                break
            fi
        done
    fi
done


if $new; then
    COLOR=$(awk '/^*blue/ {print $2}' $HOME/.Xresources)
    echo "<span fgcolor='$COLOR'>$GLYPH $count</span>"
else
    echo "$GLYPH $count"
fi
