#!/bin/bash

# Path:        ~/.dotfiles/i3/scripts/i3mocp
# Created:     25.04.18, 09:30    @manjaroi3
# Last update: 24.10.18, 19:24:18 @lenovo

# >> DOC:
# script to display in i3 status bar (i3blocks) the currently playing track (via mocp) 
# <span> markup is used for pango markup

# >> VARIABLES:
BGCOLOR=#36648b
FGCOLOR=#596473
#FGCOLOR=#6F7D91


#TITLE=$(mocp -Q %title)
#ARTIST=$(mocp -Q %artist)
#[[ $(echo $ARTIST | awk '{print $1}' | grep -i "the\|a") ]] \
#    && ARTIST=$(echo $ARTIST | awk '{print $1 " " $2}') || ARTIST=$(echo $ARTIST | awk '{print $1}')
#SONGTITLE=$(mocp -Q %song)
#[[ $(echo $SONGTITLE | awk '{print $1}' | grep -i "the\|a") ]] \
#    && SONGTITLE=$(echo $SONGTITLE | awk '{print $1 " " $2}') || SONGTITLE=$(echo $SONGTITLE | awk '{print $1}')

TRACK=$(mocp -Q %n)
[[ -n $TRACK ]] && TRACK="$TRACK. " || TRACK=""
#FILE=$(mocp -Q %file)
#FILE=${FILE##*/}
STATUS=$(mocp -Q %state)
TIME=$(mocp -Q %ct)
#LEFT=$(mocp -Q %tl)


# >> RUN:
if [ "$STATUS" != "STOP" ] && [ "$STATUS" != "" ]; then
    if [ "$STATUS" = "PLAY" ]; then
        echo -e "<span fgcolor='$BGCOLOR' weight='bold'>♫ $TRACK $TIME </span>"
    elif [ "$STATUS" = "PAUSE" ]; then
        echo -e "<span fgcolor='$FGCOLOR'>♫ $TRACK $TIME </span>"
    fi
else
    if [ "$STATUS" = "PLAY" ]; then
        echo -e "<span fgcolor='$BGCOLOR' weight='bold'>♫ $TIME </span>"
    elif [ "$STATUS" = "PAUSE" ]; then
        echo -e "♫ $TIME ♫"
    fi
fi

# >>> old run
# if [ "$STATUS" != "STOP" ] && [ "$STATUS" != "" ]; then
#     if [ "$TITLE" ]; then
#         if [ "$STATUS" = "PLAY" ]; then
#             echo -e "<span bgcolor='$BGCOLOR'>♫ $ARTIST: $SONGTITLE $TIME [-$LEFT] ♫</span>"
#         elif [ "$STATUS" = "PAUSE" ]; then
#             echo -e "<span fgcolor='$FGCOLOR'>♫ $ARTIST: $SONGTITLE $TIME [-$LEFT] ♫</span>"
#         fi
#     else
#         if [ "$STATUS" = "PLAY" ]; then
#             echo -e "<span bgcolor='$BGCOLOR'>♫ $FILE: $TIME [-$LEFT] ♫</span>"
#         elif [ "$STATUS" = "PAUSE" ]; then
#             echo -e "♫ $FILE: $TIME [-$LEFT] ♫"
#         fi
#     fi
    
# >> MOUSE:
    case $BLOCK_BUTTON in
            1) mocp -r ;; # left click = previous song
            # 2) mocp -G ;; # middle click = toggle pause/play
            2) notify-send -u low "MOCP:
=====" "$(mocp -i)";;
            3) mocp -f ;; # right click = next song
            4) mocp -k -10 ;; # scroll up = backward 10 sec
            5) mocp -k 10 ;; # scroll down = foreard 10 sec
        esac
        exit 0
else
    echo -e ""
fi

