#!/bin/bash

# Path:        ~/.dotfiles/i3/scripts/i3mocp
# Created:     25.04.18, 09:30    @manjaroi3
# Last update: 18.12.18, 20:23:58 @x200

# >> DOC:
# script to display in i3 status bar (i3blocks) the currently playing track (via mocp) 
# <span> markup is used for pango markup

# >> VARIABLES:
BGCOLOR=#36648b
FGCOLOR=#596473
#FGCOLOR=#6F7D91
if [[ $HOSTNAME == toshiba ]]; then
    GLYPH="♫"
else
    GLYPH=""
fi

TRACK=$(mocp -Q %n)
[[ -n $TRACK ]] && TRACK="$TRACK. " || TRACK=""
STATUS=$(mocp -Q %state)
TIME=$(mocp -Q %ct)

# >> RUN:
if [ "$STATUS" != "STOP" ] && [ "$STATUS" != "" ]; then
    if [ "$STATUS" = "PLAY" ]; then
        echo -e "<span fgcolor='$BGCOLOR' weight='bold'>$GLYPH $TRACK $TIME </span>"
    elif [ "$STATUS" = "PAUSE" ]; then
        echo -e "<span fgcolor='$FGCOLOR'>$GLYPH $TRACK $TIME </span>"
    fi
else
    if [ "$STATUS" = "PLAY" ]; then
        echo -e "<span fgcolor='$BGCOLOR' weight='bold'>$GLYPH $TIME </span>"
    elif [ "$STATUS" = "PAUSE" ]; then
        echo -e "$GLYPH $TIME "
    fi
fi

# >> MOUSE:

case $BLOCK_BUTTON in
    # 1) mocp -r ;; # left click = previous song
    1) mocp -G ;; # middle click = toggle pause/play
    2) mocp -f ;; # right click = next song
    3) notify-send -u low "MOCP:
=====" "$(mocp -i)";;
    4) mocp -k -10 ;; # scroll up = backward 10 sec
    5) mocp -k 10 ;; # scroll down = foreard 10 sec
esac

