#!/bin/bash

# Path:        ~/.dotfiles/i3/scripts/i3screencast-indicator
# Created:     2018-08-24, 23:09    @x200
# Last update: 2019-03-02, 21:35:11 @x200
# Doc:         i3blocks screencast indicator; runs with screencast.sh

FGCOLOR=$(cat $HOME/.Xresources | awk '/^*urgent/ {print $2}')

[[ $(ps aux | grep ffmpeg | grep -v grep) ]] &&\
    echo -e "<span color='$FGCOLOR'> </span>" || echo ""

