#!/bin/bash

# Path:        ~/.dotfiles/i3/scripts/i3uedder
# Created:     2019-03-25, 10:13    @lenovo
# Last update: 2019-03-30, 01:13:19 @lenovo
# Doc:
# Todo:        28/03/2019, condition when no wifi
#              29/03/2019, integrate wttr.in with sunapi.py (location)

SUNFILE=/tmp/suntimes
SCRIPT=$HOME/git/lab/sunapi/sunapi.sh

if [[ -f $SUNFILE ]]; then
    if [[ ! $(date +'%Y-%m-%d') ==\
            $(awk '/today:/ {print $2}' $SUNFILE) ]]
    then
        $SCRIPT > $SUNFILE
    fi
else
    $SCRIPT > $SUNFILE
fi

OUTPUT=$(
    curl -Ss 'https://wttr.in?0&T&Q' 2>/dev/null |\
        cut -c 16- |\
        head -2 |\
        xargs echo
      )

RISE=$(awk '/sunrise/ {print $2}' $SUNFILE)
SET=$(awk '/sunset/ {print $2}' $SUNFILE)
TWILIGHT=$(awk '/twilight/ {print $2}')
TIME=$(date +'%H:%M:%S')

if [[ $TIME > $TWILIGHT  && $TIME < $RISE ]]; then
    NIGHT=true
else
    NIGHT=false
fi

night_or_day() {
    $NIGHT && INDICATOR=$1 || INDICATOR=$2
}

case $OUTPUT in
    *Sunny*|*Clear*) night_or_day "" "";;
    *cloudy*|*Overcast*) INDICATOR="";;
    *Rain*) INDICATOR="☔";;
    *Snow*) INDICATOR="";;
    *) night_or_day "" "" ;;
esac

COL=$((${#OUTPUT} - 6))

[[ -n $OUTPUT ]] && echo $INDICATOR

case $BLOCK_BUTTON in
    #1 = Left, 2 = Middle, 3 = Right, 4 = Scroll Up, 5 = Scroll Down
    1) notify-send \
           -t 3000 \
           "$(printf '%s%*s%s' Wttr.in $COL $INDICATOR)" \
           "$OUTPUT
  $RISE
  $SET" &&\
             pkill -RTMIN+5 i3blocks ;;
esac
