#!/bin/bash

# Path:        ~/.dotfiles/i3/bin/i3win-title.sh
# Created:     10.07.18, 21:21    @x200
# Last update: 26.07.18, 18:41:13 @x200

# Doc:

NAME=$(xdotool getactivewindow getwindowname)
LEN=$(echo ${#NAME})
MAX=40
BGCOLOR=#191f26 # was: #00001f26

NAME_SHORT=$(echo $NAME | sed 's/ - qutebrowser$\|mpv$\|([0-9]* dpi)//g')

if (( $LEN > 0 )); then
    if (( $LEN > $MAX )); then
        let a=$LEN-$MAX
        echo "<span weight='bold'><span bgcolor='$BGCOLOR'> ${NAME_SHORT::-$a}… </span></span>"
    else
        echo "<span weight='bold'><span bgcolor='$BGCOLOR'> $NAME </span></span>"
    fi
# else
#     echo "(¬‿¬)"
fi

case $BLOCK_BUTTON in
    # left click 
    1) notify-send "Focused window title:
---------------------" "<i>$NAME</i>\ncopied to clipboard" && i3-msg "exec --no-startup-id echo '$NAME' | xclip -selection c && exit 1";;
esac

