#!/bin/bash

# Path:        ~/.bin/i3wifi.sh
# Created:     10.07.18, 14:37    @x200
# Last update: 02.12.18, 15:27:45 @x200

# >> DOC:

# >> COND:
IF=$(ip route | awk '/^default/ { print $5 ; exit }')
[[ -z $IF ]] && echo "OFF"

# >> VARIABLES:
COLOR="#C0392B"

if [[ $IF == "enp0s25" ]]; then
    GLYPH=""
    QUALITY=$(dmesg | grep $IF | grep Up | awk 'NR==1 {print $8 " " $9}')
else
    GLYPH="" # ▼
    QUALITY=$(grep $IF /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
fi

CONN=$(ping -q -w 1 -c 1 $(ip r | grep default | cut -d ' ' -f 3 | head -n 1))
#CONN=$(ping -c 1 1.1.1.1 2>/dev/null)

#PAC_LOSS=$(ping -q -w 1 -c 1 $(ip r | grep default | cut -d ' ' -f 3) | awk 'NR==4 {print $6}' | sed 's/%//g')

# >> i3blocks OUTPUT
# >> 1.
if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
    # NOTE: może to jest lepsze rozwiązanie niż moje CONN? 
    #if [[ ! $(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3`) ]]; then
    echo "<span fgcolor='$COLOR'>$GLYPH down</span>"
    # update dropbox status @i3blocks
    pkill -RTMIN+13 i3blocks
    exit
fi

# >> 2.
if [[ $(echo $CONN | grep Unreachable) ]]; then
    # <span bgcolor='#00001f26'></span>
    echo "<span color='$COLOR'>$GLYPH ?</span>"
    # update dropbox status @i3blocks
    pkill -RTMIN+13 i3blocks

elif [[ $(echo $CONN | grep '0 received') ]]; then
    echo "<span color='$COLOR'>$GLYPH ${QUALITY}</span>"
    # update dropbox status @i3blocks
    pkill -RTMIN+13 i3blocks
else
    echo "$GLYPH ${QUALITY}"
fi

# >> MOUSE BEHAVIOUR
case $BLOCK_BUTTON in
    # left click 
    1) notify-send -u low "Dropbox status:
--------------" "$(dropbox-cli status)" -i ~/box/Dropbox/.Config/dropbox-logo.png && exit 0
       # update dropbox status @i3blocks
       pkill -RTMIN+13 i3blocks
       ;;
esac
