#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

bold=$(tput bold)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
RESET=$(tput sgr0)

#PS1='[\u@\h \W]\$ '
PS1='${bold}${RED}[\u${RESET} ${GREEN}\w${bold}${RED}]\$${RESET} '

if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi

shopt -s autocd

export EDITOR='/usr/bin/emacsclient -nw'

