#!/bin/bash

# Path:        ~/.dotfiles/fish/b
# Created:     2019-03-13, 08:58    @toshiba
# Last update: 2019-03-13, 09:33:10 @toshiba
# Doc:         bash wrapper for fish
# Caveat:      use "@" instead of "$" because fish will complain or try to
#              substitute command

args="${@//@/$}"
eval "${args}"
