

abbr --add gB ~/biu
abbr --add gC ~/.config
abbr --add gD ~/box/Dropbox/Dokumenty
abbr --add gaa ~/dwl
abbr --add gag ~/dwl/att
abbr --add gcf ~/.config/fish
abbr --add gcm ~/.config/neomutt
abbr --add gcn ~/.newsboat
abbr --add gcq ~/.config/qutebrowser
abbr --add gcr ~/.config/ranger
abbr --add gct ~/.config/termite
abbr --add gcl ~/.config/lf
abbr --add gcx ~/.config/xfce4
abbr --add gdb ~/.dotfiles/bin
abbr --add gdd ~/.dotfiles
abbr --add gdf ~/.dotfiles/fish
abbr --add gdi ~/.dotfiles/i3
abbr --add gdq ~/.dotfiles/qtbro
abbr --add gdr ~/.dotfiles/ranger
abbr --add ged ~/.emacs.d
abbr --add geg ~/git/hub/emacs
abbr --add geh ~/git/hub/heder
abbr --add ggg ~/git
abbr --add ggh ~/git/hub
abbr --add ggl ~/git/lab
abbr --add ggp ~/git/lab/py-exercises
abbr --add ggs ~/git/hub/st
abbr --add ggo ~/go
abbr --add gh ~
abbr --add gm ~/muz
abbr --add gob ~/obr
abbr --add goo ~/org
abbr --add gp ~/pdf
abbr --add gsc ~/scr
abbr --add gwe ~/web
abbr --add gws ~/web/schole
abbr --add gww ~/wid
abbr --add gwt ~/web/test
abbr --add gxc ~/box/Dropbox/.Config
abbr --add gxd ~/box/Dropbox/Dokumenty
abbr --add gxs ~/box/Dropbox/Szkoła
abbr --add gxx ~/box/Dropbox
abbr --add gxw ~/box/Dropbox/Wiki
abbr --add gx@ ~/box/Dropbox/Web
abbr --add gxb ~/box/Dropbox/Biurko
abbr --add gxp ~/box/Dropbox/Programowanie
abbr --add gxr ~/box/Dropbox/Projekty

