

abbr --add gB /home/piotr/biu
abbr --add gC /home/piotr/.config
abbr --add gD /home/piotr/box/Dropbox/Dokumenty
abbr --add gS /home/piotr/szk
abbr --add ga /home/piotr/dwl
abbr --add gaa /home/piotr/dwl
abbr --add gag /home/piotr/dwl/att
abbr --add gb /home/piotr/bin
abbr --add gbi /home/piotr/bin
abbr --add gcf /home/piotr/.config/fish
abbr --add gcm /home/piotr/.config/neomutt
abbr --add gcn /home/piotr/.newsboat
abbr --add gcq /home/piotr/.config/qutebrowser
abbr --add gcr /home/piotr/.config/ranger
abbr --add gct /home/piotr/.config/termite
abbr --add gcx /home/piotr/.config/xfce4
abbr --add gd /home/piotr/.dotfiles
abbr --add gdb /home/piotr/.dotfiles/bin
abbr --add gdd /home/piotr/.dotfiles
abbr --add gdf /home/piotr/.dotfiles/fish
abbr --add gdi /home/piotr/.dotfiles/i3
abbr --add gdq /home/piotr/.dotfiles/qtbro
abbr --add gdr /home/piotr/.dotfiles/ranger
abbr --add geH /home/piotr/git/hub/hobbit
abbr --add ged /home/piotr/.emacs.d
abbr --add geg /home/piotr/git/hub/emacs
abbr --add geh /home/piotr/git/hub/heder
abbr --add gf /home/piotr/gfx
abbr --add gg /home/piotr/git
abbr --add ggh /home/piotr/git/hub
abbr --add ggl /home/piotr/git/lab
abbr --add ggp /home/piotr/git/lab/py-exercises
abbr --add ggs /home/piotr/git/hub/st
abbr --add gh /home/piotr
abbr --add gm /home/piotr/muz
abbr --add gob /home/piotr/obr
abbr --add goo /home/piotr/org
abbr --add gop /home/piotr/org/pro
abbr --add gp /home/piotr/pdf
abbr --add gsc /home/piotr/scr
abbr --add gsf /home/piotr/szk/flz
abbr --add gsr /home/piotr/szk/rtk
abbr --add gss /home/piotr/szk
abbr --add gsz /home/piotr/szk/18-19
abbr --add gwe /home/piotr/web
abbr --add gws /home/piotr/web/schole
abbr --add gww /home/piotr/wid
abbr --add gwt /home/piotr/web/test
abbr --add gx /home/piotr/box/Dropbox
abbr --add gxc /home/piotr/box/Dropbox/.Config
abbr --add gxd /home/piotr/box/Dropbox/Dokumenty
abbr --add gxs /home/piotr/box/Dropbox/Szkoła
abbr --add gxx /home/piotr/box/Dropbox
abbr --add gxw /home/piotr/box/Dropbox/Wiki
abbr --add gx@ /home/piotr/box/Dropbox/Web
abbr --add gxb /home/piotr/box/Dropbox/Biurko
abbr --add gxp /home/piotr/box/Dropbox/Programowanie

